#!/bin/sh
# IceWM startup file
# This script is run at the start of an IceWM session.
# Add your startup commands below.


# Start the picom compositor
picom --config ~/.config/picom.conf &

feh --randomize --bg-scale $HOME/.icewm/themes/IceWM-RedZen/backgrounds/*